#region License

// Copyright (c) 2013, MatrixPACS Inc.
// All rights reserved.
// http://www.MatrixPACS.ca
//
// This file is part of the MatrixPACS RIS/PACS open source project.
//
// The MatrixPACS RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The MatrixPACS RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the MatrixPACS RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

// This file is auto-generated by the MatrixPACS.Model.SqlServer.CodeGenerator project.

namespace MatrixPACS.ImageServer.Model
{
    using System;
    using System.Collections.Generic;
    using MatrixPACS.ImageServer.Model.EntityBrokers;
    using MatrixPACS.ImageServer.Enterprise;
    using System.Reflection;

[Serializable]
public partial class ArchiveQueueStatusEnum : ServerEnum
{
      #region Private Static Members
      private static readonly ArchiveQueueStatusEnum _Pending = GetEnum("Pending");
      private static readonly ArchiveQueueStatusEnum _InProgress = GetEnum("In Progress");
      private static readonly ArchiveQueueStatusEnum _Completed = GetEnum("Completed");
      private static readonly ArchiveQueueStatusEnum _Failed = GetEnum("Failed");
      #endregion

      #region Public Static Properties
      /// <summary>
      /// Pending
      /// </summary>
      public static ArchiveQueueStatusEnum Pending
      {
          get { return _Pending; }
      }
      /// <summary>
      /// In Progress
      /// </summary>
      public static ArchiveQueueStatusEnum InProgress
      {
          get { return _InProgress; }
      }
      /// <summary>
      /// The Queue entry is completed.
      /// </summary>
      public static ArchiveQueueStatusEnum Completed
      {
          get { return _Completed; }
      }
      /// <summary>
      /// The Queue entry has failed.
      /// </summary>
      public static ArchiveQueueStatusEnum Failed
      {
          get { return _Failed; }
      }

      #endregion

      #region Constructors
      public ArchiveQueueStatusEnum():base("ArchiveQueueStatusEnum")
      {}
      #endregion
      #region Public Members
      public override void SetEnum(short val)
      {
          ServerEnumHelper<ArchiveQueueStatusEnum, IArchiveQueueStatusEnumBroker>.SetEnum(this, val);
      }
      static public List<ArchiveQueueStatusEnum> GetAll()
      {
          return ServerEnumHelper<ArchiveQueueStatusEnum, IArchiveQueueStatusEnumBroker>.GetAll();
      }
      static public ArchiveQueueStatusEnum GetEnum(string lookup)
      {
          return ServerEnumHelper<ArchiveQueueStatusEnum, IArchiveQueueStatusEnumBroker>.GetEnum(lookup);
      }
      #endregion
}
}
