#region License

// Copyright (c) 2013, MatrixPACS Inc.
// All rights reserved.
// http://www.MatrixPACS.ca
//
// This file is part of the MatrixPACS RIS/PACS open source project.
//
// The MatrixPACS RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The MatrixPACS RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the MatrixPACS RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

// This file is auto-generated by the MatrixPACS.Model.SqlServer.CodeGenerator project.

namespace MatrixPACS.ImageServer.Model
{
    using System;
    using System.Xml;
    using MatrixPACS.Enterprise.Core;
    using MatrixPACS.ImageServer.Enterprise;
    using MatrixPACS.ImageServer.Enterprise.Command;
    using MatrixPACS.ImageServer.Model.EntityBrokers;

    [Serializable]
    public partial class ProcedureCode: ServerEntity
    {
        #region Constructors
        public ProcedureCode():base("ProcedureCode")
        {}
        public ProcedureCode(
             ServerEntityKey _serverPartitionKey_
            ,String _identifier_
            ,String _text_
            ,String _codingSystem_
            ):base("ProcedureCode")
        {
            ServerPartitionKey = _serverPartitionKey_;
            Identifier = _identifier_;
            Text = _text_;
            CodingSystem = _codingSystem_;
        }
        #endregion

        #region Public Properties
        [EntityFieldDatabaseMappingAttribute(TableName="ProcedureCode", ColumnName="ServerPartitionGUID")]
        public ServerEntityKey ServerPartitionKey
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="ProcedureCode", ColumnName="Identifier")]
        public String Identifier
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="ProcedureCode", ColumnName="Text")]
        public String Text
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="ProcedureCode", ColumnName="CodingSystem")]
        public String CodingSystem
        { get; set; }
        #endregion

        #region Static Methods
        static public ProcedureCode Load(ServerEntityKey key)
        {
            using (var context = new ServerExecutionContext())
            {
                return Load(context.ReadContext, key);
            }
        }
        static public ProcedureCode Load(IPersistenceContext read, ServerEntityKey key)
        {
            var broker = read.GetBroker<IProcedureCodeEntityBroker>();
            ProcedureCode theObject = broker.Load(key);
            return theObject;
        }
        static public ProcedureCode Insert(ProcedureCode entity)
        {
            using (var update = PersistentStoreRegistry.GetDefaultStore().OpenUpdateContext(UpdateContextSyncMode.Flush))
            {
                ProcedureCode newEntity = Insert(update, entity);
                update.Commit();
                return newEntity;
            }
        }
        static public ProcedureCode Insert(IUpdateContext update, ProcedureCode entity)
        {
            var broker = update.GetBroker<IProcedureCodeEntityBroker>();
            var updateColumns = new ProcedureCodeUpdateColumns();
            updateColumns.ServerPartitionKey = entity.ServerPartitionKey;
            updateColumns.Identifier = entity.Identifier;
            updateColumns.Text = entity.Text;
            updateColumns.CodingSystem = entity.CodingSystem;
            ProcedureCode newEntity = broker.Insert(updateColumns);
            return newEntity;
        }
        #endregion
    }
}
