#region License

// Copyright (c) 2013, MatrixPACS Inc.
// All rights reserved.
// http://www.MatrixPACS.ca
//
// This file is part of the MatrixPACS RIS/PACS open source project.
//
// The MatrixPACS RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The MatrixPACS RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the MatrixPACS RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

// This file is auto-generated by the MatrixPACS.Model.SqlServer.CodeGenerator project.

namespace MatrixPACS.ImageServer.Model.EntityBrokers
{
    using System;
    using System.Xml;
    using MatrixPACS.Enterprise.Core;
    using MatrixPACS.ImageServer.Enterprise;

    public partial class ArchiveStudyStorageSelectCriteria : EntitySelectCriteria
    {
        public ArchiveStudyStorageSelectCriteria()
        : base("ArchiveStudyStorage")
        {}
        public ArchiveStudyStorageSelectCriteria(ArchiveStudyStorageSelectCriteria other)
        : base(other)
        {}
        public override object Clone()
        {
            return new ArchiveStudyStorageSelectCriteria(this);
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ArchiveStudyStorage", ColumnName="PartitionArchiveGUID")]
        public ISearchCondition<ServerEntityKey> PartitionArchiveKey
        {
            get
            {
              if (!SubCriteria.ContainsKey("PartitionArchiveKey"))
              {
                 SubCriteria["PartitionArchiveKey"] = new SearchCondition<ServerEntityKey>("PartitionArchiveKey");
              }
              return (ISearchCondition<ServerEntityKey>)SubCriteria["PartitionArchiveKey"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ArchiveStudyStorage", ColumnName="StudyStorageGUID")]
        public ISearchCondition<ServerEntityKey> StudyStorageKey
        {
            get
            {
              if (!SubCriteria.ContainsKey("StudyStorageKey"))
              {
                 SubCriteria["StudyStorageKey"] = new SearchCondition<ServerEntityKey>("StudyStorageKey");
              }
              return (ISearchCondition<ServerEntityKey>)SubCriteria["StudyStorageKey"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ArchiveStudyStorage", ColumnName="ServerTransferSyntaxGUID")]
        public ISearchCondition<ServerEntityKey> ServerTransferSyntaxKey
        {
            get
            {
              if (!SubCriteria.ContainsKey("ServerTransferSyntaxKey"))
              {
                 SubCriteria["ServerTransferSyntaxKey"] = new SearchCondition<ServerEntityKey>("ServerTransferSyntaxKey");
              }
              return (ISearchCondition<ServerEntityKey>)SubCriteria["ServerTransferSyntaxKey"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ArchiveStudyStorage", ColumnName="ArchiveTime")]
        public ISearchCondition<DateTime> ArchiveTime
        {
            get
            {
              if (!SubCriteria.ContainsKey("ArchiveTime"))
              {
                 SubCriteria["ArchiveTime"] = new SearchCondition<DateTime>("ArchiveTime");
              }
              return (ISearchCondition<DateTime>)SubCriteria["ArchiveTime"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ArchiveStudyStorage", ColumnName="ArchiveXml")]
        public ISearchCondition<XmlDocument> ArchiveXml
        {
            get
            {
              if (!SubCriteria.ContainsKey("ArchiveXml"))
              {
                 SubCriteria["ArchiveXml"] = new SearchCondition<XmlDocument>("ArchiveXml");
              }
              return (ISearchCondition<XmlDocument>)SubCriteria["ArchiveXml"];
            } 
        }
    }
}
