#region License

// Copyright (c) 2013, MatrixPACS Inc.
// All rights reserved.
// http://www.MatrixPACS.ca
//
// This file is part of the MatrixPACS RIS/PACS open source project.
//
// The MatrixPACS RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The MatrixPACS RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the MatrixPACS RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

// This file is auto-generated by the MatrixPACS.Model.SqlServer.CodeGenerator project.

namespace MatrixPACS.ImageServer.Model.EntityBrokers
{
    using System;
    using System.Xml;
    using MatrixPACS.ImageServer.Enterprise;

   public partial class FilesystemUpdateColumns : EntityUpdateColumns
   {
       public FilesystemUpdateColumns()
       : base("Filesystem")
       {}
        [EntityFieldDatabaseMappingAttribute(TableName="Filesystem", ColumnName="FilesystemPath")]
        public String FilesystemPath
        {
            set { SubParameters["FilesystemPath"] = new EntityUpdateColumn<String>("FilesystemPath", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Filesystem", ColumnName="Enabled")]
        public Boolean Enabled
        {
            set { SubParameters["Enabled"] = new EntityUpdateColumn<Boolean>("Enabled", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Filesystem", ColumnName="ReadOnly")]
        public Boolean ReadOnly
        {
            set { SubParameters["ReadOnly"] = new EntityUpdateColumn<Boolean>("ReadOnly", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Filesystem", ColumnName="WriteOnly")]
        public Boolean WriteOnly
        {
            set { SubParameters["WriteOnly"] = new EntityUpdateColumn<Boolean>("WriteOnly", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Filesystem", ColumnName="FilesystemTierEnum")]
        public FilesystemTierEnum FilesystemTierEnum
        {
            set { SubParameters["FilesystemTierEnum"] = new EntityUpdateColumn<FilesystemTierEnum>("FilesystemTierEnum", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Filesystem", ColumnName="LowWatermark")]
        public Decimal LowWatermark
        {
            set { SubParameters["LowWatermark"] = new EntityUpdateColumn<Decimal>("LowWatermark", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Filesystem", ColumnName="HighWatermark")]
        public Decimal HighWatermark
        {
            set { SubParameters["HighWatermark"] = new EntityUpdateColumn<Decimal>("HighWatermark", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Filesystem", ColumnName="Description")]
        public String Description
        {
            set { SubParameters["Description"] = new EntityUpdateColumn<String>("Description", value); }
        }
    }
}
